package hwwallet

import (
	"github.com/btcsuite/btcd/chaincfg"
	"time"

	"github.com/lightningnetwork/lnd/lnwallet"
)

// Config is a struct which houses configuration parameters which modify the
// instance of BtcWallet generated by the New() function.
type Config struct {
	// DataDir is the name of the directory where the wallet's persistent
	// state should be stored.
	DataDir string

	// Birthday specifies the time at which this wallet was initially
	// created. It is used to bound rescans for used addresses.
	Birthday time.Time

	// RecoveryWindow specifies the address look-ahead for which to scan
	// when restoring a wallet. The recovery window will apply to all
	// default BIP44 derivation paths.
	RecoveryWindow uint32

	// FeeEstimator is an instance of the fee estimator interface which
	// will be used by the wallet to dynamically set transaction fees when
	// crafting transactions.
	FeeEstimator lnwallet.FeeEstimator

	// CoinType specifies the BIP 44 coin type to be used for derivation.
	CoinType uint32

	// NetParams is the net parameters for the target chain.
	NetParams *chaincfg.Params

	// connection information for the remote wallet RPC service
	RemoteAddress string
}
